<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Magento\OfflinePayments\Block\Info\Purchaseorder
 */
?>
<dl class="payment-method purchase order" style="font-size: 18px;">
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <dd class="content" style="margin-left:0">
        <strong><?= $block->escapeHtml(__('Purchase Order Number')) ?></strong>
        <span class="number"><?= $block->escapeHtml($block->getInfo()->getPoNumber()) ?></span>
    </dd>
</dl>
