<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
use Magento\Catalog\Pricing\Price\TierPrice;
use Magento\Framework\Pricing\Amount\AmountInterface;
?>


<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */
// Daily deal Helper
$helper=$this->helper('Smartwave\Dailydeals\Helper\Data');

$productId = $block->getSaleableItem()->getId();



/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;

$saleableItem = $block->getSaleableItem();
/** @var TierPrice $price */
$price = $saleableItem->getPriceInfo()->getPrice(TierPrice::PRICE_CODE);
$tierPriceList = $price->getTierPriceList();
$tierPrices = [];
foreach ($tierPriceList as $tierPrice) {
    /** @var AmountInterface $price */
    $price = $tierPrice['price'];
    $tierPrices[] = $price->getValue();
}

$maxPrice = null;

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/** @var \Magento\Framework\Pricing\Adjustment\CalculatorInterface $calculator */
$calculator = $objectManager->get(\Magento\Framework\Pricing\Adjustment\CalculatorInterface::class);
$maxPriceAmount = $calculator->getAmount($maxPrice, $saleableItem, 'tax');
?>
<?php if($helper->isDealProduct($productId)) : ?>
    <?php
    $deal_final_price_amount = number_format($helper->getDealproductbyId($productId),2);
    ?>
    <span class="old-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
    <span class="special-price">
        <span class="price-container price-final_price tax weee">
            <span class="price-label">Special Price</span>
            <span id="product-price-<?php echo $idSuffix; ?>" data-price-amount="<?php echo $deal_final_price_amount; ?>" data-price-type="finalPrice" class="price-wrapper ">
                <span class="price"><?php echo $helper->getcurrencySymbol().''.$deal_final_price_amount; ?></span>
            </span>
        </span>
    </span>
<?php elseif ($block->hasSpecialPrice()): ?>
    <span class="old-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
    <span class="special-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Special Price'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
<?php else : ?>
    <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
<?php endif; ?>


<?php if($maxPrice): ?>
<a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="maximal-price-link">
    <?= /* @noEscape */
    $block->renderAmount($maxPriceAmount, [
        'display_label' => __(''),
        'include_container' => false,
        'skip_adjustments' => true
    ]) ?>
</a>
<?php endif; ?>