<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Magento\Catalog\Block\Product\View */
/** @var Amasty\HidePrice\Helper\Data $hidePriceHelper */
$hidePriceHelper = \Magento\Framework\App\ObjectManager::getInstance()->get(\Amasty\HidePrice\Helper\Data::class);
if (!$block->getProduct() || $hidePriceHelper->isNeedHidePrice($block->getProduct())) {
    return;
}
?>
<?php
$required = '';
if ($block->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . $block->escapeHtmlAttr(__('* Required Fields')) . '"';
}
?>
<div class="product-options-wrapper" id="product-options-wrapper"<?= /* @noEscape */ $required ?>>
    <div class="fieldset" tabindex="0">
        <?= $block->getChildHtml('', true) ?>
    </div>
</div>
